### ISSUE TITLE
 Consider an exclusion for appengine-api-1.0-sdk in bigtable-client-parent

### ISSUE THREAD

**Issue by sduskis** [googleapis/cloud-bigtable-client#1271]
There's currently a dependency chain from bigtable-client-parent through google-auth-library-appengine [1] to appengine-api-1.0-sdk [2] which pulls in quite a lot of unnecessary stuff.

A user brought this up reporting a 17MB size increase of their dependencies

Is this something we can/should prevent with an exclusion on the dependency?

[1] https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/pom.xml#L174
[2] https://github.com/google/google-auth-library-java/blob/master/pom.xml#L83

**Comment by rahulKQL** [comment]
@sduskis /@kolea2, I think this issue can be marked closed.  The `appengine` is now migrated using `google-http-client-appengine` jar.

Please let me know If this issue is still valid in some way.
