### ISSUE TITLE
Log uses of older versions

### ISSUE THREAD

**Issue by sduskis** [googleapis/cloud-bigtable-client#1319]
We should keep a file somewhere that has the version number of the stable release.  We should write a log of some sort if a user is using an older version.

**Comment by rahulKQL** [comment]
@sduskis and @igorbernstein2 Do we want to implement this feature? 
If yes, then Should we maintain a specific file with just versions? OR Can we use existing `bigtable-versions.properties` file?

**Comment by igorbernstein2** [comment]
I think this will require quite a bit of thought & design. Also, this should be done in google-cloud-java across all clients. I think we should just close this issue for now
