### ISSUE TITLE
Add static analysis to find bugs sooner

### ISSUE THREAD

**Issue by mbrukman** [googleapis/cloud-bigtable-client#1517]
Static analysis tools enable finding and avoiding bugs at compile time, before they become issues at runtime, and become much harder (and hence, costlier) to find and fix.

There are tools that can be run offline, such as SpotBugs (successor to FindBugs) and [ErrorProne](http://errorprone.info/), or via online services such as [Coverity](https://scan.coverity.com/) (free for open-source projects). Wikipedia has a [list static analysis tools for Java](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#Java).

FWIW, we've integrated Coverity scans into JanusGraph builds, though ended up not using the Travis CI integration with Coverity; here is how it was done:

* [`.travis.yml`](https://github.com/JanusGraph/janusgraph/blob/master/.travis.yml)
* [analysis script and Dockerfile](https://github.com/JanusGraph/janusgraph/tree/master/analysis) referenced in `.travis.yml` — note that CentOS appears to behave differently from Ubuntu for Coverity

I'm happy to add Coverity support for this repo, if there's interest and support (please vote with 👍 / 👎).

Thoughts?

**Comment by sduskis** [comment]
I manually ran ErrorProne on our two largest projects.  I found some minor legit issues as well as nuisance type problems.  Igor pointed out that we need to have a significant effort in adding annotations like Nullable, GuardedBy and etc. to make this work.

I agree in concept that this is a Good Thing (tm), but I'm not sure about the priority.
