### ISSUE TITLE
Reduce impact of channel refreshing

### ISSUE THREAD

**Issue by sduskis** [googleapis/cloud-bigtable-client#1735]
When a channel shuts down and reconnect, the service will throw an `UNAVAILABLE` or something like it with a "Go Away" message. That happens on a scheduled bases for all long running Channels.

When the shutdown happens and `UNAVAILBLE` is returned, an RPC retry is triggered.  Since we have a `ChannelPool`, the RPC will likely be tried on a different channel.  In a low QPS system or large machines (that have a lot of CPUs, and therefore a proportionally larger channel pool), that new channel is likely to also be shut down, and the cycle will start again.  This can happen a few times, which would mean that the total operation time could become large.

Towards that end, add stats and spans that could be sent via OpenCensus's tracing and statistics around the refreshing.  Also, consider a policy other than round-robin for channel selection in these cases.

**Comment by bogdandrutu** [comment]
Couple of thoughts/suggestions:
* I think with the current bigtable_client + grpc instrumentation you should see the first RPC client span that fails and then immediately a new RPC client span that succeed. Is that the case?
* Do you think an attribute on the RPC client span that tells if the RPC started a new channel connection when executed would help?
* Do you have other suggestions?

**Comment by sduskis** [comment]
As far as telemetry is concerned:

- We do have traces across RPCs if there was a retry, assuming that we're lucky enough to get traces for those RPCs.
- We probably need an annotation for shutdown and reconnects, and stats around connection retries.

**Comment by sduskis** [comment]
This is probably something that [grpc-gcp](https://github.com/GoogleCloudPlatform/grpc-gcp-java) should do, and not something actionable for this repository.
