### ISSUE TITLE
Create an option to use google-cloud-bigtable under the covers.

### ISSUE THREAD

**Issue by sduskis** [googleapis/cloud-bigtable-client#1769]
As [google-cloud-bigtable](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-bigtable) matures, we will need to start migrating the HBase client to use it, instead of bigtable-client-core. 

Ideally the two clients would live side by side during the transition. This would allow for smoother transition path for our users and allow us to test the clients. We can accomplish this by implementing [BigtableDataClient](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableDataClient.java) interface using google-cloud-bigtable. And update the hbase layer use either implementation using a config option.

**Comment by sduskis** [comment]
@igorbernstein2 any additional context would be useful.

**Comment by igorbernstein2** [comment]
I added an initial proposal for it. I'll flesh it out in the next couple of weeks

**Comment by sduskis** [comment]
This is still a work in progress.
