### ISSUE TITLE
no way to programatically set credentials when using cbt emulator

### ISSUE THREAD

**Issue by juhanicc** [googleapis/cloud-bigtable-client#1957]
Using BIGTABLE_EMULATOR_HOST is a reasonable solution for trying things out, but when using something like testcontainers to unit test with cbt emulator in a container with an unpredictable port it's not possible to set environment variables.

It would be very helpful if there was a way to set credentials programatically as can be done with BigtableOptions in the normal client, or GoogleCredentials and similar with storage and other products.

**Comment by juhanicc** [comment]
On further investigation it appears that this can be done with something like:

btConf.set(BigtableOptionsFactory.BIGTABLE_EMULATOR_HOST_KEY, BIGTABLE.getContainerIpAddress() + ":" +
                BIGTABLE.getMappedPort(testPort).toString());

I arrived by this looking at past issues and the debugger, but it would be  good if this was documented

**Comment by igorbernstein2** [comment]
Hi @juhanicc, I was wondering if https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-testing/google-cloud-bigtable-emulator would fit your usecase?
