### ISSUE TITLE
Watchdog idle timeout cannot be configured

### ISSUE THREAD

**Issue by Naveg** [googleapis/cloud-bigtable-client#2123]
We have some scans with sparse filters than can run for a long time before returning any data (tens of minutes). Accordingly, we have set `READ_PARTIAL_ROW_TIMEOUT_MS` to an appropriately high value.

Since the introduction of `Watchdog`, there appears to be a floor of 10 minutes on the timeout, and this is causing some of our scans to fail before they encounter data.

BigtableSession creates a Watchdog using the 2-argument constructor, here:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/8576d5cb5d6156bd1ac102de5acf280fe43d6b0f/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java#L290-L291

The third argument, which controls the idle timeout, is not used. So the idle timeout remains the default 10 minutes:

https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/8576d5cb5d6156bd1ac102de5acf280fe43d6b0f/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/io/Watchdog.java#L80-L88

Our scans fail here:

https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/8576d5cb5d6156bd1ac102de5acf280fe43d6b0f/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/io/Watchdog.java#L215-L221

Prior to the introduction of watchdog, it looks like there was only one timeout, which was configurable via `READ_PARTIAL_ROW_TIMEOUT_MS`

See also https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1921#issuecomment-417415741 for some prior discussion.

**Comment by sduskis** [comment]
Sorry for the delay in the response.

IDLE happens when there are no outstanding requests.  This is probably not a `Watchdog` problem, and probably tricky to solve.

**Comment by Naveg** [comment]
Do you mean that increasing the idle timeout beyond 10 minutes would cause the scan to fail elsewhere? Or are you suggesting that these long-running scans will hang and never complete, regardless of the timeout?

I had thought a possible solution could be to set idleTimeoutMs to the greater of `DEFAULT_IDLE_TIMEOUT_MS` and `waitTimeoutMs`

**Comment by sduskis** [comment]
IDLE is supposed to mean that there aren't any expected responses from the server-side.  I wouldn't expect that to happen unless there are results in memory that have not been processed.

**Comment by sduskis** [comment]
I think I actually got a fix for this.  I wasn't quite clear on the situation before my last comment.  Basically, there are two states the `Watchdog` could timeout it:

1. `WAITING` - The server-side is slow, which is controlled by `READ_PARTIAL_ROW_TIMEOUT_MS`
2. `IDLE` - The client-side is slow, which happens after 10 minutes of client-side processing without fetching a new batch from the server-side.

The `Watchdog` introduced a nice abstraction around `WAITING`, and added `IDLE`.  We didn't retry on `IDLE`.  I'm working on a PR to fix that, and do a retry after an IDLE timeout.  Also, I'm going to add more OpenCensus annotations for `WAITING` / `IDLE` timeouts.

**Comment by Naveg** [comment]
Interesting. We've actually turned off retries, since we were finding that scans would time out after not returning any data, only to retry and timeout again.

**Comment by sduskis** [comment]
The general retry mechanism is meant to retry on transient network failures.  The `IDLE` retry is a bit different, since it relates to user "inactivity" or expensive processing.

I would suggest turning on OpenCensus tracing for large scale scans so that you can get more debugging information.  (see https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/tracing-hello-world)

**Comment by Naveg** [comment]
Thanks for the link - I'll look into turning on the OpenCensus tracing. So, just to confirm - this fix causes a retry on IDLE regardless of the `MAX_SCAN_TIMEOUT_RETRIES` setting?

**Comment by sduskis** [comment]
The change I made will do a retry only if the user asks for more data via the `ResultScanner.getNext()`.  It will ignore `MAX_SCAN_TIMEOUT_RETRIES`.

**Comment by sduskis** [comment]
I released a new SNAPSHOT version of the client (1.10.1-SNAPSHOT) with this chage.  Please feel free to try it out.  I'm going to close this issue.  Please reopen this issue (or create a new one) if this pops up again.
