### ISSUE TITLE
UNAUTHENTICATED error writing to BigTable with GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by hilliao** [googleapis/cloud-bigtable-client#2150]
in pom.xml, if I specify the following version, running Dataflow DirectRunner with GOOGLE_APPLICATION_CREDENTIALS that has BigTable admin role would result in UNAUTHENTICATED error

```
  <dependency>
			<groupId>com.google.cloud.bigtable</groupId>
			<artifactId>bigtable-hbase-beam</artifactId>
			<version>1.10.0</version>
		</dependency>
```
[The output](https://drive.google.com/file/d/1b0AsU1orf9AVKu-vpRNnSEABzyZElhYT/view?usp=sharing) contains many retry errors of com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential
**The fix is to change the pom.xml section to** 
```
<dependency>
			<groupId>com.google.cloud.bigtable</groupId>
			<artifactId>bigtable-hbase-beam</artifactId>
			<version>1.5.0</version>
		</dependency>
```
[The output](https://drive.google.com/file/d/1C7nFOkIWSTIwHva25b4_DF-cnLeVO2tU/view?usp=sharing) does not contain retry errors writing to BigTable

Please update your README.md to use the 1.5.0 version as an example so developers don't have to dig around to find [the official doc](https://cloud.google.com/bigtable/docs/hbase-dataflow-java) to add the 1.5.0 version. Is 1.10.0 broken by nature?

**Comment by rahulKQL** [comment]
@hilliao,
I just ran few dataflow runner jobs with `bigtable-hbase-beam-1.10.0` version, those all worked fine for me. I am unable to re-create this issue at my end.

I also saw that you were using beam version `2.11.0`. Could you please try again with the combination of bigtable version `1.10.0` and beam version `2.9.0`.

**Comment by hilliao** [comment]
I modified pom.xml per your request. The console output is after the pom.xml's content [HERE](https://drive.google.com/file/d/1yU4EmbV8HkEmHUUaulLcFvcKl_67PXa3/view?usp=sharing). No luck. I am running locally with DirectRunner that reads from pub sub and writes to BigTable. My environment variable GOOGLE_APPLICATION_CREDENTIALS is set properly for pub sub to read events. In debugger, DataflowPipelineOptions.getGcpCredential() returns clientEmail="local-runner@[my project ID].iam.gserviceaccount.com" which is the correct service account I set. Are you running with DirectRunner>

**Comment by sduskis** [comment]
@rahulKQL, I don't think that the Beam version is the problem.  This is likely something that relates to the client itself.  

As of `bigtable-client-1.7.0` we started using JWT instead of using service accounts directly.  That might be the problem.

@hilliao, I'm confused by why you've mentioned the Cloud Bigtable admin role.  Beam integration usually only use data permissions, and not admin.

**Comment by hilliao** [comment]
I used that BigTable admin role for a different purpose. I could use BigTable user role that has the read,write data permission. The  BigTable admin role has more permissions and should not be the related to the issue here. The service account used here have the following roles:

- Bigtable Administrator
- Dataflow Admin
- Dataflow Worker
- Pub/Sub Publisher
- Pub/Sub Subscriber
- Pub/Sub Viewer
- Viewer

I tried with 1.6.0 and 1.7.0 and reproduced the same UNAUTHENTICATED error. I have the full code zip files in issue #2151. Please follow the steps there for local runner, set GOOGLE_APPLICATION_CREDENTIALS, and execute
> export GOOGLE_APPLICATION_CREDENTIALS=path/to/your/service-account-secret.json
> mvn exec:java -Dexec.mainClass=com.finack.app.FinackPipeline -Dexec.args=" --project=mwpfin --runner=DirectRunner --mode=debug "

Only --mode=debug  will give you multiple UNAUTHENTICATED error in the console output after publishing at least 2 messages. With or without  --mode=debug, the results are the same: fail to process further pub/sub messages. Are you able to reproduce it running my code?

**Comment by hilliao** [comment]
I tried to reproduce this problem in Cloud Dataflow and found this bug may not happen. I follow the workaound @sduskis  to change pom.xml so Cloud dataflow worker can start properly.

> mvn   exec:java       -Dexec.mainClass=com.finack.app.FinackPipeline        -Dexec.args="--project=mwpfin       --stagingLocation=gs://mwpfin-tmp/github2151/       --runner=DataflowRunner       --mode=dataflow       --serviceAccount=local-runner@mwpfin.iam.gserviceaccount.com --jobName=bt-1-10-0"

Per [Controller service account](https://cloud.google.com/dataflow/docs/concepts/security-and-permissions#controller_service_account), the following image shows my job's worker is running as local-runner@mwpfin.iam.gserviceaccount.com
![image](https://user-images.githubusercontent.com/1208650/56398312-ac302500-61fc-11e9-915d-991ff5df8d8c.png)
it's able to read from pub/sub and write to BigTable. If you agree my testing was accurate, I will close this issue. it's not blocking our progress locally since we can use user credentials. @sduskis  said it's likely the local client causing the issue. Where can I look to configure or upgrade my client?

**Comment by liufuyang** [comment]
I think I encountered the same issue here... 🤔

**Comment by liufuyang** [comment]
@sduskis would you mind help take a look at my issue above? Thank you :)

**Comment by liufuyang** [comment]
Looks like if I change Apache Beam SDK for Java 2.13.0 to 2.11.0, then I don't get this bigtable read permission denied errors... wondering why that helps? 🤔

**Comment by sduskis** [comment]
@liufuyang can you please open up a new issue?

**Comment by liufuyang** [comment]
I will give a try :)

**Comment by igorbernstein2** [comment]
For future reference, version >= 1.11.1-SNAPSHOT of the bigtable client have a workaround. I will release version 1.12.0 next week
