### ISSUE TITLE
bigtable-hbase-beam causes Dataflow job worker to fail

### ISSUE THREAD

**Issue by hilliao** [googleapis/cloud-bigtable-client#2151]
**problem statement**
with the following maven pom.xml dependency, Cloud Dataflow job worker fails to start.
```
<dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-beam</artifactId>
            <version>1.5.0</version>
        </dependency>
```
The workaround is to delete the above section in pom.xml and related Java code. Below is the error in Dataflow's StackDriver logging:
> Error syncing pod 414461ba254099a817d81f7d60657139 ("dataflow-debugme-worker-fails-04181156-lbcm-harness-g5rz_default(414461ba254099a817d81f7d60657139)"), skipping: failed to "StartContainer" for "java-streaming" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=java-streaming pod=dataflow-debugme-worker-fails-04181156-lbcm-harness-g5rz_default(414461ba254099a817d81f7d60657139)"

**The source** is [bigtable-beam-dataflow-worker-fail.zip](https://drive.google.com/file/d/10J8-6AaB3cAX52B-5a27HCg0nq-ap5s8/view?usp=sharing).

To reproduce the bug, modify com/finack/models/Constants.java with the correct pub/sub subscriptions, project ID, BigTable instance:

- PROJECT_ID
- PUBSUB_SUBSCRIPTION_TO_PIPELINE
- BIGTABLE_CLOUD_INSTANCE_ID
- CFAMILY # column family for the table
- TABLE_ID

Create a BigTable and pub/sub subscription per the fields above. Execute the following to run locally:
> mvn   exec:java       -Dexec.mainClass=com.finack.app.FinackPipeline        -Dexec.args="  --project=mwpfin --runner=DirectRunner --mode=debug " # --mode=debug is optional, without it, console output will be less verbose

If local runner executes without error, publish to the topic linked to the subscription and verify messages enter BigTable:

1. Download the [publish.py](https://drive.google.com/file/d/19C7rq1oWP0sPPobFg-MgmT8w5vKlgnE_/view?usp=sharing) module.
2. edit the first 2 lines of publish.py to put the correct project ID and topic.
3. Every run will create a pub sub message with current timestamp.

Ideally, messages will write to BigTable. Then kill the local runner and execute the following command to run with DataflowRunner. Put a cloud storage path for --stagingLocation=
`mvn   exec:java   -Dexec.mainClass=com.finack.app.FinackPipeline        -Dexec.args="--project=mwpfin       --stagingLocation=gs://tmp/staging/       --runner=DataflowRunner       --mode=dataflow "  `

Observe the error from StackDriver logging:
![image](https://user-images.githubusercontent.com/1208650/56391481-a1b56180-61e3-11e9-9503-6cf804095b4c.png)
![image](https://user-images.githubusercontent.com/1208650/56391509-c01b5d00-61e3-11e9-83ec-d2365d04d6ac.png)
The job appears to be running but does not write to BigTable. I proved BigTable dependency was the cause because of the following:
Code without that dependency and write to System.out.println method instead of BigTable would not have the **Error syncing pod** errors.

I have not been able to access the compute engine node or the failed pod to debug further. I can't find documentation that shows how. Maybe that's not possible. Are you able to reproduce?

**Comment by sduskis** [comment]
I think that that started happening with Bean 2.10. We had a fix in our 1.10 release (see [here](https://github.com/googleapis/cloud-bigtable-client/commit/a1846950a551de4b0404c03eeb83bbbae6724ee1)).  It looks like we haven't released that in an official version.  I'll do that shortly

**Comment by sduskis** [comment]
Try adding this to your `bigtable-beam-hbase` dependency:

```
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
```

That worked for us . That ought to work for you as well even for the 1.5.0 release

**Comment by hilliao** [comment]
Thank you so much, @sduskis ! After putting the following to pom.xml, Cloud dataflow runner inserts to Bigtable.
```
<dependency>
            <groupId>com.google.cloud.bigtable</groupId>
            <artifactId>bigtable-hbase-beam</artifactId>
            <version>1.5.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
The problem is there is no logging at all in Stackdriver for the running job which is insanely painful:
![image](https://user-images.githubusercontent.com/1208650/56397969-4000f180-61fb-11e9-831b-0d8f22b67b3b.png)

![image](https://user-images.githubusercontent.com/1208650/56398000-5c9d2980-61fb-11e9-89bf-76b0c6146089.png)

I think  SLF4J is what Dataflow uses for general logging to Stackdriver such as worker messages. With the pom.xml change above, logging to console with System.out.println along with SLF4J did not create any log entries. Neither did any Dataflow system log entries. Do you have a workaround to restore logging before the fix is official?

**Comment by sduskis** [comment]
I think that you need to use a newer version of `slf4j-log4j12` that's compatible with Beam.  As best as I can tell, Beam is using slf4j `1.7.25`.

**Comment by hilliao** [comment]
I suppose you did not read [my source zip file](https://drive.google.com/file/d/10J8-6AaB3cAX52B-5a27HCg0nq-ap5s8/view?usp=sharing) that contains in pom.xml

```
<beam.version>2.11.0</beam.version>
<slf4j.version>1.7.25</slf4j.version>
```
I believe the cause is slf4j-log4j12 is excluded from the project classpath. Since there is no slf4j-log4j12, Dataflow can't log to Stackdriver. 

1. When Do you plan to release the fix for bigtable-hbase-beam?
2. Will the fix cause no StackDriver logging?

**Comment by sduskis** [comment]
@hilliao, I'm sorry that didn't work.  I have no idea why you can't log.  Can you please ask the Beam community?  See methods of communicating with them here: https://beam.apache.org/community/contact-us/

**Comment by hilliao** [comment]
I found the fix to enable StackDriver logging:
replace
```
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>${slf4j.version}</version>
            <!-- When loaded at runtime this will wire up slf4j to the JUL backend -->
            <scope>runtime</scope>
        </dependency>
```
with 
```
<dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
```
On behalf of Maven wave partners (Google cloud north America service of 2018), we Thank @sduskis.
