### ISSUE TITLE
CloudBigtableTableConfiguration does not accept ValueProvider<String>

### ISSUE THREAD

**Issue by hilliao** [googleapis/cloud-bigtable-client#2155]
[CloudBigtableTableConfiguration.java](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableTableConfiguration.java) has 
`public Builder withInstanceId(String instanceId) ` but `    Builder withInstanceId(ValueProvider<String> instanceId) ` is not public. My current project needs to [create template](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates) by passing runtime parameters similar to [the stackoverflow](https://stackoverflow.com/questions/48500976/how-can-i-pass-runtime-parameters-to-bigtableio-in-java) page. here's how I use it:
```
new CloudBigtableTableConfiguration.Builder()
                .withProjectId(options.getProject())
                .withInstanceId(options.getBigtableInstanceID()) // accepting ValueProvider<String>
                .withTableId(options.getBigtableID()) // accepting ValueProvider<String>
                .build();
```

**Comment by skraelings** [comment]
@hilliao did this work for you?
I am trying to create a template and running into the issue
`Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider`

**Comment by hilliao** [comment]
I have left the project and the employer at the time. I checked [the latest source](https://github.com/googleapis/java-bigtable-hbase/blob/master/bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableTableConfiguration.java). It has become public:

```
 @Override
    public Builder withInstanceId(ValueProvider<String> instanceId) {
      super.withInstanceId(instanceId);
      return this;
    }
```

I suppose I would be able to compile but @skraelings 's error is more like accessing the BigTable instance ID from some hard coded value at compile time. It's highly likely you called .get() on the ValueProvider before pipeline execution according to [creating-templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates)

> If you call get() before pipeline execution, Apache Beam returns an error:
> Value only available at runtime, but accessed from a non-runtime context.

After you fix your code, [running-templates](https://cloud.google.com/dataflow/docs/guides/templates/running-templates) tells you to use 

> --parameters inputFile

as in 

> gcloud dataflow jobs run JOB_NAME \
>         --gcs-location gs://YOUR_BUCKET_NAME/templates/MyTemplate \
>         --parameters inputFile=gs://YOUR_BUCKET_NAME/input/my_input.txt,outputFile=gs://YOUR_BUCKET_NAME/output/my_output

Question to @sduskis : 
Why is the following code using --input, --output? Shouldn't it be --inputFile, --outputFile to be consistent with the Java sample code at [creating-templates](https://cloud.google.com/dataflow/docs/guides/templates/creating-templates)?

```
class WordcountOptions(PipelineOptions):
    @classmethod
    def _add_argparse_args(cls, parser):
      # Use add_value_provider_argument for arguments to be templatable
      # Use add_argument as usual for non-templatable arguments
      parser.add_value_provider_argument(
          '--input',
          default='gs://dataflow-samples/shakespeare/kinglear.txt',
          help='Path of the file to read from')
      parser.add_argument(
          '--output',
          required=True,
          help='Output file to write results to.')
  pipeline_options = PipelineOptions(['--output', 'some/output_path'])
  p = beam.Pipeline(options=pipeline_options)
  wordcount_options = pipeline_options.view_as(WordcountOptions)
  lines = p | 'read' >> ReadFromText(wordcount_options.input)
```

**Comment by skraelings** [comment]
I am not terrible familiar with the code base. I saw the changes in #2158 and I think _validate_ as well as _getTableId_ should have been modified, similar to what BigtableIO does which allows it to be nullable.

`/** Returns the table being read from. */
    @Nullable
    public String getTableId() {
      ValueProvider<String> tableId = getBigtableConfig().getTableId();
      return tableId != null && tableId.isAccessible() ? tableId.get() : null;
    }`
