### ISSUE TITLE
Scan.setColumnFamilyTimeRange is silently ignored

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/cloud-bigtable-client#2184]
As reported in https://www.google.com/url?q=http://stackoverflow.com/questions/56979965&sa=D&usg=AFQjCNHf0BNJP5jWTOFDPgHVStmIJcmGnA

The ScanAdapter should be updated to either throw an exception if Scan#getColumnFamilyTimeRange() is set or we should update the ScanAdapter to adapt the families & ranges into filters

**Comment by rahulKQL** [comment]
Closing this issue as this is address with #2185.
