### ISSUE TITLE
 Can CachedThreadPool "bigtable-batch-pool" create too much threads?

### ISSUE THREAD

**Issue by xiang9156** [googleapis/cloud-bigtable-client#2219]
Client: com.google.cloud.bigtable:bigtable-hbase-1.x-shaded:1.3.0

Problem:
Hi, 
Looks like BigtableSessionSharedThreadPools creates cached thread pool called "bigtable-batch-pool" by default. What's the usage of it? Will it create too much threads under certain case? Is it configurable to use fixed size pool?

Thanks,
Xiang

**Comment by rahulKQL** [comment]
`BigtableSessionSharedThreadPools#batchThreadPool` is used to provide the batching capability for reading rows from bigtable under BulkRead. It creates threads as per the need only [here](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSessionSharedThreadPools.java#L25-L26). 

> Will it create too much threads under certain case? 

Here a _too much thread_ could vary per user and as per the number of records to read(using `ReadRowsRequest`). I think It would only occur if the user is continuously making read and flush calls between very little duration.

> Is it configurable to use fixed size pool?

No, As of yet there is no way to configure "bigtable-batch-pool" thread pool size.

**Comment by xiang9156** [comment]
Hi @rahulKQL ,

Thanks for your response! 
We do batch read(a few hundred rows) and batch mutation (around 3000 rows) every 10-15 seconds. 
I'm wondering how a new thread is created? 1 thread per batch or 1 thread per row? 
If there's network issue or BT issues in GCP, can it cause thousands of threads being created?

Thanks,
Xiang

**Comment by rahulKQL** [comment]
> I'm wondering how a new thread is created? 1 thread per batch or 1 thread per row?

For both batches(i.e. read and mutation) It will submit 1 thread per batch, Here one batch means accumulated elements(`MutateRowsRequest`s/`ReadRowsRequest`s) being sent over RPC by calling flush() or after triggering any present thresholds(`BulkOptions#maxRequestCount`/`BulkOptions#maxRequestSize`).

>If there's network issue or BT issues in GCP, can it cause thousands of threads being created?

As batchThreadPool is `cachedThreadPool`, So idle connections will be reused if the threads are waiting and it will be closed in 60 seconds of default idle time.
 
Personally, I have not come across any scenario when any user has that many threads with a few thousand rows read/mutate. It also depends on the number of mutations per row, this client currently supports 100_000 mutation per row.

Adding @igorbernstein2  for more input.

**Comment by igorbernstein2** [comment]
I'm going to close this, since it doesn't seem like there is aproblem.

You can inspect thread counts using something like jconsole. If you notice that the threads are growing unbounded, please reopen this issue.
